# Generated by Django 2.1.4 on 2018-12-22 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set1', models.CharField(max_length=3)),
                ('set2', models.CharField(max_length=3)),
                ('set3', models.CharField(max_length=3)),
                ('set4', models.CharField(max_length=3)),
                ('set5', models.CharField(max_length=3)),
                ('result1', models.CharField(max_length=1)),
                ('result2', models.CharField(max_length=1)),
                ('date_of_occ', models.DateTimeField(verbose_name='Date of occurrence')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateTimeField(verbose_name='Date of birth')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date of occurrence')),
                ('hometeam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hometeam', to='Register.Team')),
                ('hostteam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hostteam', to='Register.Team')),
                ('match1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match1', to='Register.Match')),
                ('match10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match10', to='Register.Match')),
                ('match11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match11', to='Register.Match')),
                ('match12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match12', to='Register.Match')),
                ('match13', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match13', to='Register.Match')),
                ('match14', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match14', to='Register.Match')),
                ('match15', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match15', to='Register.Match')),
                ('match16', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match16', to='Register.Match')),
                ('match2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match2', to='Register.Match')),
                ('match3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match3', to='Register.Match')),
                ('match4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match4', to='Register.Match')),
                ('match5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match5', to='Register.Match')),
                ('match6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match6', to='Register.Match')),
                ('match7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match7', to='Register.Match')),
                ('match8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match8', to='Register.Match')),
                ('match9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='match9', to='Register.Match')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='victor', to='Register.Team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Register.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='Register.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='Register.Player'),
        ),
    ]
