# Generated by Django 2.1.4 on 2018-12-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammatch',
            old_name='date',
            new_name='date_of_match',
        ),
    ]
