# Generated by Django 2.1.4 on 2018-12-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0003_auto_20181226_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.CharField(choices=[('DL', 'District League'), ('RL', 'Regional League'), ('SL', 'State League'), ('EL', 'Extra League')], max_length=20, null=True),
        ),
    ]
