# Generated by Django 2.1.4 on 2018-12-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0004_team_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammatch',
            name='hometeam',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='hostteam',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match1',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match10',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match11',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match12',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match13',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match14',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match15',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match16',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match2',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match3',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match4',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match5',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match6',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match7',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match8',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='match9',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='winner',
        ),
        migrations.DeleteModel(
            name='TeamMatch',
        ),
    ]
