# Generated by Django 2.1.4 on 2018-12-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0006_auto_20181227_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='set1',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='set2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='set3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='set4',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='set5',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
