# Generated by Django 2.1.4 on 2018-12-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register', '0007_auto_20181227_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='result1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result2',
        ),
    ]
